name: Cypress Tests

on:
  push:
    branches:
      - master

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      # Check out the code
      - name: Check out code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Explicitly install Cypress binary (forces Cypress to download and install the binary)
      - name: Install Cypress binary
        run: npx cypress install

      # Cache Cypress binary (cache the path where Cypress is installed)
      - name: Cache Cypress binary
        uses: actions/cache@v3
        with:
          path: ~/.cache/Cypress
          key: ${{ runner.os }}-Cypress-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-Cypress-

      # Run Cypress tests
      - name: Run Cypress tests
        run: npx cypress run


      - name: Zip Reports
        run: zip -r cypress-reports.zip cypress/reports

      - name: Upload Test Reports
        uses: actions/upload-artifact@v3
        with:
          name: cypress-reports
          path: cypress-reports.zip

      - name: Push Report to GitHub Pages
        if: always()
        env:
          GH_TOKEN: ${{ secrets.MY_DEMOQA }}  
        run: |