name: Cypress Tests

on:
  push:
    branches:
      - master  # Ejecutar pruebas cuando se hagan cambios en la rama "main"
  pull_request:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
  
    steps:
      # Checkout el código fuente
      - name: Checkout code
        uses: actions/checkout@v3

      # Configurar Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.14.0  # Usa la versión de Node.js que necesites

      # Instalar dependencias
      - name: Install dependencies
        run: npm install

      # Ejecutar las pruebas de Cypress
      - name: Run Cypress tests
        run: npx cypress run

      # Subir informes de Cypress como artefactos (opcional)
      - name: Upload Test Reports
        if: always()  # Ejecutar incluso si las pruebas fallan
        uses: actions/upload-artifact@v3
        with:
          name: cypress-reports
          path: cypress/reports
